version: '3.8'

services:
  text2sql-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: text2sql-assistant
    ports:
      - "8501:8501"
    environment:
      # Application Configuration
      - APP_NAME=Text-to-SQL Assistant
      - DATABASE_URL=sqlite:///app/data/demo.sqlite
      - MODEL_NAME=google/flan-t5-base
      - MODEL_CACHE_DIR=/app/models
      - MAX_TOKENS=128
      - NUM_BEAMS=4
      - MAX_INPUT_LENGTH=400
      
      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_THEME_BASE=light
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
      
      # Performance Configuration
      - ENABLE_MODEL_CACHING=true
      - MODEL_LOAD_TIMEOUT=60
      - QUERY_TIMEOUT=30
      
      # Safety Configuration
      - DEFAULT_QUERY_LIMIT=200
      - MAX_QUERY_LIMIT=10000
      - ENABLE_SAFETY_CHECKS=true
      
      # Logging
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/app.log
      
      # Python Configuration
      - PYTHONPATH=/app/src:/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    volumes:
      # Persistent data storage
      - text2sql_data:/app/data
      - text2sql_models:/app/models
      - text2sql_logs:/app/logs
      
      # Optional: Mount source code for development
      # - ../src:/app/src:ro
      # - ../config:/app/config:ro
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

volumes:
  text2sql_data:
    driver: local
  text2sql_models:
    driver: local
  text2sql_logs:
    driver: local

networks:
  default:
    name: text2sql-network
